services:
  node-red:
    image: nodered/node-red
    restart: always
    hostname: node-red
    container_name: mynodered
    user: "0"
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Brussels
    volumes:
       - ./node-red/data:/data
    networks:
      - iot
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    volumes:
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto/log:/mosquitto/log/
    ports:
      - "1883:1883"
    networks:
      - iot
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - iot
    # Comment if you don't have a GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
  iot:
    driver: bridge