services:
  node-red:
    image: nodered/node-red
    restart: always
    hostname: node-red
    container_name: mynodered
    user: "0"
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Brussels
    volumes:
       - ./node-red/data:/data
    networks:
      - iot
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"  # Zookeeper escucha en este puerto
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - iot
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    volumes:
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto/log:/mosquitto/log/
    ports:
      - "1883:1883"
    networks:
      - iot
  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    ports:
      - "9092:9092"  # Kafka escucha en este puerto
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - iot
networks:
  iot:
    driver: bridge